### PR TITLE
(updated repo exists so this is useless)

### PR DESCRIPTION
**Pull request by dz-void**
Most commits have no description/vague sorry

### CODE REVIEW

**Comment by SnowzNZ** [comment]
Some of these programs can be and should be installed by scoop, e.g: notepad++, obs, etc. Then whenever there is an update there is no need to update the batch files.

Not sure if there is a scoop installation batch file, but if not you should probably create one, or have it try to install in the batch file to install the program

**Comment by he3als** [comment]
give an overall description of what has changed

**Comment by dz-void** [comment]
> Some of these programs can be and should be installed by scoop, e.g: notepad++, obs, etc. Then whenever there is an update there is no need to update the batch files.
> 
> Not sure if there is a scoop installation batch file, but if not you should probably create one, or have it try to install in the batch file to install the program

Valid

**Comment by dz-void** [comment]
i forgot about the updated repo 💀

**Pull request closed without merging**
